# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UserName = QtWidgets.QLabel(self.centralwidget)
        self.UserName.setGeometry(QtCore.QRect(188, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UserName.setFont(font)
        self.UserName.setFrameShape(QtWidgets.QFrame.Box)
        self.UserName.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserName.setLineWidth(2)
        self.UserName.setObjectName("UserName")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(272, 234, 113, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.PassWord = QtWidgets.QLabel(self.centralwidget)
        self.PassWord.setGeometry(QtCore.QRect(188, 266, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PassWord.setFont(font)
        self.PassWord.setFrameShape(QtWidgets.QFrame.Box)
        self.PassWord.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PassWord.setLineWidth(2)
        self.PassWord.setObjectName("PassWord")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(272, 270, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Login_Button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.loginButton())
        self.Login_Button.setGeometry(QtCore.QRect(250, 310, 75, 24))
        self.Login_Button.setObjectName("Login_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuMist_Login = QtWidgets.QMenu(self.menubar)
        self.menuMist_Login.setObjectName("menuMist_Login")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMist_Login.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def loginButton(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UserName.setText(_translate("MainWindow", "Username"))
        self.PassWord.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Login Page"))
        self.Login_Button.setText(_translate("MainWindow", "Login"))
        self.menuMist_Login.setTitle(_translate("MainWindow", "Mist Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
